### ISSUE TITLE
post请求需要发送哪些属性给这个服务

### ISSUE THREAD

**Issue by bugensui2022** [yaming116/FunAsr#5]
您好，请教下。已经部署好了。我内网的程序，需要用到这个服务，用于语音识别文字，是winodws主机，我发post请求，到api端口，需要发送哪些参数？

**Comment by yaming116** [comment]
file: 音频文件， 其他的不需要

**Comment by bugensui2022** [comment]
> file: 音频文件， 其他的不需要

谢谢，支持base64的吗，还是一定要file
